{% set version = "0.7.9" %}

package:
  name: genshi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/G/Genshi/Genshi-{{ version }}.tar.gz
  sha256: c76170a8b2dc18944e0915103c284cb889dfcee34e0e140ba3363c80f7541ad2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - genshi
    - genshi.filters
    - genshi.template
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://genshi.edgewall.org/
  summary: A toolkit for generation of output for the web
  doc_url: https://pythonhosted.org/Genshi/
  license: BSD-3-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - ocefpaf
