{% set version = "0.7.7" %}

package:
  name: genshi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/G/Genshi/Genshi-{{ version }}.tar.gz
  sha256: c100520862cd69085d10ee1a87e91289e7f59f6b3d9bd622bf58b2804e6b9aab

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    # - doctools
  run:
    - python
    - six

test:
  imports:
    - genshi
    - genshi.filters
    - genshi.template
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://genshi.edgewall.org/
  summary: A toolkit for generation of output for the web
  doc_url: https://pythonhosted.org/Genshi/
  license: BSD-3-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - ocefpaf
